import type { HomeContent } from './types';

export const homeEn: HomeContent = {
  hero: {
    name: '小柳璃紗',
    romaji: 'Risa Koyanagi',
    eyebrow: 'Space · Nuclear · Cyber · Emerging Technology Governance',
    title: 'Researcher · Platform Builder',
    description: [
      { text: 'Risa Koyanagi is a ' },
      { text: 'student / researcher at University of Cambridge', strong: true },
      { text: ' working across ' },
      { text: 'space, nuclear, and emerging technology governance', strong: true },
      { text: '. Her work focuses on ' },
      { text: 'legitimation', strong: true },
      { text: ', ' },
      { text: 'dual-use systems', strong: true },
      { text: ', and ' },
      { text: 'authority architecture', strong: true },
      { text: '. She also designs ' },
      { text: 'public-facing research platforms', strong: true },
      { text: ' on ' },
      { text: 'AI governance', strong: true },
      { text: ', ' },
      { text: 'strategic infrastructure risk', strong: true },
      { text: ', and ' },
      { text: 'interpretive systems', strong: true },
      { text: '.' },
    ],
    ctaPlatforms: 'View Platforms',
    ctaResearch: 'View Research',
    linkedinLabel: 'LinkedIn',
    instagramLabel: 'Instagram',
    githubLabel: 'GitHub',
    contactLabel: 'Contact',
    photoAlt: 'Risa Koyanagi',
  },
  platforms: {
    header: { kanji: '台', english: 'Platforms by Risa Koyanagi' },
    flagshipLabel: 'Flagship',
    viewPlatform: 'View platform →',
    wipLabel: 'WIP',
    viewAll: 'View all platforms →',
    items: [
      {
        title: 'Cyber Escalation Atlas',
        href: '/platforms/cyber',
        liveUrl: 'https://cyber-escalation-atlas-5yp5.vercel.app',
        description: 'Mapping cyber incidents as strategic behaviour, attribution frameworks, and governance signals.',
        image: '/images/cyber-platform.png',
        imageAlt: 'Cyber Escalation Atlas',
      },
      {
        title: 'Narrative Drift',
        href: '/platforms/narrative-drift',
        liveUrl: 'https://narrative-drift.vercel.app/',
        description: 'AI influence on choice, memory, and self-understanding over time.',
        image: '/images/narrative drift-og.png',
        imageAlt: 'Narrative Drift',
      },
      {
        title: 'SelfTrace',
        href: '/platforms/selftrace',
        liveUrl: 'https://selftrace.vercel.app/',
        description: 'Algorithmic shaping of identity, self-presentation, and online selfhood.',
        image: '/images/selftrace og.png',
        imageAlt: 'SelfTrace',
      },
      {
        title: 'Ontological Governance Observatory',
        href: '/platforms/ontological-governance-observatory',
        description: 'AI\'s transformation of the human subject across epistemic, ontological, and political layers.',
        image: '/images/ogo-og.png',
        imageAlt: 'Ontological Governance Observatory',
      },
      {
        title: 'Orbital Risk Tracker',
        href: '/platforms/orbital',
        liveUrl: 'https://orbitalrisktracker.vercel.app',
        description: 'ASAT events, proximity operations, and escalation analysis in orbital space.',
        image: '/images/orbital-platform.jpg',
        imageAlt: 'Orbital Risk Tracker',
      },
      {
        title: 'Global Nuclear Infrastructure Atlas',
        href: '/platforms/nuclear',
        liveUrl: 'https://globalnuclearinfrastructureatlas.vercel.app',
        description: 'Civilian nuclear infrastructure, estimated arsenals, and policy and health context.',
        image: '/images/nuclear-platform.jpg',
        imageAlt: 'Global Nuclear Infrastructure Atlas',
      },
      {
        title: 'Lunar Mandate Atlas',
        href: '/platforms/lunar-mandate-atlas',
        liveUrl: 'https://lunar-mandate-atlas.vercel.app',
        description: 'Competing governance claims, mandates, and authority architecture on the Moon.',
        image: '/images/LGAT-og.svg',
        imageAlt: 'Lunar Mandate Atlas',
      },
      {
        title: 'MYTHERA',
        href: '/platforms/mythera',
        liveUrl: 'https://mythera.vercel.app/',
        description: 'An interpretive studio where selfhood, culture, performance, and aesthetic form become explorable worlds.',
        image: '/images/mythera og.png',
        imageAlt: 'MYTHERA',
        children: [
          {
            name: 'Theatre of Authenticity',
            href: '/platforms/theatre-of-authenticity',
            description: 'Questioning authenticity through experiential design — performance, gaze, and the limits of the "true self"',
            status: 'In Progress',
            image: '/images/Theatre of Authenticity.png',
            imageAlt: 'Theatre of Authenticity',
          },
          {
            name: 'Second Self',
            href: '/platforms/second-self',
            description: 'A philosophical card game exploring AI, memory, governance, and the formation of subjectivity',
            status: 'In Progress',
            image: '/images/secondself_og.png',
            imageAlt: 'Second Self',
          },
        ],
      },
    ],
  },
  research: {
    header: { kanji: '論', english: 'Research', subtitle: 'Selected research across governance domains' },
    viewAll: 'View all research →',
    items: [
      {
        href: '/research/lunar',
        title: 'Who Speaks for Humanity on the Moon?',
        description: 'Examining legitimation audiences, translation devices, and authority architecture in competing lunar governance frameworks.',
      },
      {
        href: '/research/ai-cyber',
        title: 'Responsible Behaviour as an Unfinished Norm',
        description: 'Investigating denial, displacement, and inoculation in AI governance discourse across space, AI, and cyber domains.',
      },
      {
        href: '/research/fukushima',
        title: 'Post-Disaster Governance and the Trust Gap',
        description: 'Long-term fieldwork examining policy gaps, trust, and recovery governance in post-disaster Fukushima communities.',
      },
    ],
  },
  conference: {
    header: {
      kanji: '壇',
      english: 'Selected Conference Presentations',
      subtitle: 'Forthcoming papers and panels at international research convenings',
    },
    data: {
      event: 'IAC 2026 — 3 Accepted Papers',
      location: 'Antalya, Türkiye',
      organizer: 'International Astronautical Congress · Organized by the International Astronautical Federation (IAF)',
      highlight: '3 Accepted Papers',
      tags: ['Space Governance', 'Lunar Systems', 'Norms', 'Dual-Use'],
      papers: [
        {
          title: 'Dual-Use Neutralisation and Responsible Behaviour Norms in Lunar Infrastructure Governance',
          type: 'Oral Presentation',
          symposium: 'E9 — Space Security, Stability and Sustainability',
          date: '8 October 2026',
        },
        {
          title: 'Conditional Openness: How Universalist Language Produces Boundaries in Future Lunar Exploration Governance',
          type: 'Interactive Presentation',
          symposium: 'E3 — Space Policy, Regulations and Economics',
        },
        {
          title: 'Mythic Naming as Soft Infrastructure in Competing Lunar Orders: Artemis and Chang’e',
          type: 'Interactive Presentation',
          symposium: 'E5 — Space and Society',
        },
      ],
      focus: 'lunar governance, dual-use systems, norm formation, and symbolic infrastructure in emerging space orders.',
    },
  },
  fieldwork: {
    header: {
      kanji: '場',
      english: 'Fieldwork & Public Engagement',
      subtitle: 'Fieldwork, leadership, dialogue, and public-facing engagement across policy, research, and international exchange',
    },
    projects: [
      {
        href: '/projects/fukushima',
        title: 'Fukushima Field Research',
        description: 'Multi-site fieldwork in Futaba and Namie districts examining post-disaster governance, trust, and recovery.',
        image: '/images/fukushima.jpg',
        imageAlt: 'Fukushima fieldwork',
        period: '2019–2024',
      },
      {
        href: '/projects/afrecos',
        title: 'AFRECOS',
        description: 'Co-founded a 10+ country network for cultural and policy events bridging Africa and Japan.',
        image: '/images/afrecos.jpg',
        imageAlt: 'AFRECOS',
        period: '2024',
        role: 'Co-Founder & President',
      },
      {
        href: '/projects/art',
        title: 'Art Practice',
        description: 'Interdisciplinary art practice spanning visual thinking, international exhibition, and conceptual work.',
        image: '/images/art.JPG',
        imageAlt: 'Art practice',
      },
    ],
    speakingHeading: 'Speaking & Policy Engagement',
    speaking: [
      {
        title: 'TICAD Ministerial Meeting',
        context: 'Policy engagement and youth representation at the Tokyo International Conference on African Development.',
        type: 'Policy Engagement',
        image: '/images/speaking-ticad.jpg',
      },
      {
        title: 'Japan–Netherlands Peace Exchange',
        context: 'Bilateral dialogue and peace exchange between Japanese and Dutch participants.',
        type: 'Dialogue Contribution',
        image: '/images/speaking-peace-exchange.jpg',
      },
      {
        title: 'Africa–Japan Youth Drive',
        context: 'Youth-focused policy forum addressing Africa–Japan co-creation and development cooperation.',
        type: 'Youth Representation',
        image: '/images/speaking-youth-drive.jpg',
      },
      {
        title: 'Roundtable and Friends of Education',
        context: 'Hosted by GPE and the World Bank at the Japanese House of Councillors.',
        type: 'Roundtable Participation',
        image: '/images/speaking-roundtable.JPG',
      },
    ],
    viewAll: 'View all fieldwork & engagement →',
  },
};
